apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-devops-project
  template:
    metadata:
      labels:
        app: jenkins-devops-project
    spec:
      containers:
      - name: jenkins-devops-project
        image: 604969/jenkins-devops-project:1.0.0-17
        ports:
        - containerPort: 8080

